name: CI
on: [push]
jobs:
    build:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['20.x']
                # node: ['16.x', '18.x', '20.x'] - no need to test other versions
                os: [ubuntu-latest]
                # os: [ubuntu-latest, windows-latest, macOS-latest] - no need to test other os

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - name: Install
              run: pnpm install

            - name: Build
              run: pnpm build

            - name: Test
              run: pnpm vitest --run
